### ISSUE TITLE
Could you add freedom mobile to the APN list

### ISSUE THREAD

**Issue by jeffjiang1998** [RiwiHow/FixChinaCarrier#12]
Hello,

I could not find freedom mobile in the APN config file.
Could you add freedom mobile in the APN config file? Thanks,
Will this working on Andriod 12 system? I am using Lenovo legion Y70.

Here is the setting for freedom mobile:

    <apn carrier="Internet"
         mcc="302"
         mnc="490"
         apn="internet.freedommobile.ca"
         type="default,dun,agps,supl,fota,hipri"
         protocol="IPV4V6"
    />
    <apn carrier="MMS"
         mcc="302"
         mnc="490"
         apn="mms.freedommobile.ca"
         type="mms"
         mmsc="http://mms.freedommobile.ca"
         mmsproxy="74.115.197.70"
         mmsport="8080"
    />

**Comment by RiwiHow** [comment]
The `apns-conf.xml` file for this module was extracted from a Chinese version of MIUI, which may not include Freedom Mobile APN settings. However, this module specifically addresses slow internet speeds on Chinese carriers, where 'slow' refers to speeds of around 10 KB per second. If you are not experiencing issues with such slow internet speed, there is no need for you to install this module. 😉
But, if you insist on adding the APN file for Freedom Mobile, I could certainly try to add it.

**Comment by jeffjiang1998** [comment]
Thanks. I actually add it in the APN file and recompile it myself by using your package. It actually replace the APN config file in the system. But I still have problem to connect to my mobile data.  The APN for my carrier is blank. When I also try to add new APN, it cannot save it.

![Screenshot_20231025-080718](https://github.com/RiwiHow/FixChinaCarrier/assets/38994095/5b3a1d23-0779-4c84-9775-879f2e470940)


![Screenshot_20231025-080531](https://github.com/RiwiHow/FixChinaCarrier/assets/38994095/842ed1a3-34fa-4ca9-a28b-ad7a960cdf1e)

**Comment by RiwiHow** [comment]
Apologies for any confusion, but I'm not entirely clear on how Android interprets `apns-conf.xml`. All I know is how to substitute it. 🥲

I wonder if this could be due to an incomplete configuration file. I've just taken a look at the `apns-conf.xml` file from the European version of MIUI, and I didn't come across any reference to `freedommobile`. I'm not sure what the Canadian equivalent would be, but I know that for MIUI there are various versions like the Global, European, Indian, Chinese etc. Perhaps you might consider extracting this file from your specific version of the system, such as these versions of MIUI, and then replacing the corresponding file in the module?

**Comment by jeffjiang1998** [comment]
I also tried other apns-conf.xml file. It replaces the file in the system/etc folder but the problem still exist. Maybe it is due to the Rom issue. Anyway, thanks for your help.
